#!/bin/bash

# Add line separator after shell command to delimit servers list
ansible -m shell -a "curl --version && echo --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------" servers

# Check for docker installation
ansible -m shell -a "ps xua |grep docker && echo --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------" servers
